apiVersion: security.istio.io/v1
kind: RequestAuthentication
metadata:
  name: jwt-auth
  namespace: cnd-dev
spec:
  selector:
    matchLabels:
      gateway.networking.k8s.io/gateway-name: cnd-ingress-gateway #jwt-auth는 gateway에 걸려야한다
  jwtRules:
    - issuer: "cnd-dev"   # JwtProvider에서 설정한 iss 값과 동일해야 함
      #jwksUri: "http://member-service.cnd-dev.svc.cluster.local:80/.well-known/jwks.json"
      jwksUri: "http://host.docker.internal:8081/.well-known/jwks.json"
      fromHeaders:
        - name: Authorization
          prefix: "Bearer "
      outputClaimToHeaders:
        - claim: sub
          header: x-cnd-username
        - claim: roles
          header: x-cnd-roles
