spring:
  application:
    name: cnd-lea-lp

  data:
    redis:
      host: host.docker.internal

  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    #url: jdbc:log4jdbc:mariadb://localhost:3306/cnd?CharacterEncoding=UTF-8
    url: jdbc:log4jdbc:mariadb://host.docker.internal:3306/cnd?CharacterEncoding=UTF-8
    username: viaura
    password: money

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: never

jwt:
  secret: ${JWT_SECRET:defaultSecretValue}
  access-token-validity-seconds: ${JWT_ACCESS_TOKEN_VALIDITY:1209600}  # 14일
  refresh-token-validity-seconds: ${JWT_REFRESH_TOKEN_VALIDITY:2592000} # 30일
  issuer: ${JWT_ISSUER:cnd-dev}



logging:
  file:
    name: logs/cnd-lea-lp.log
  level:
    root: INFO
    com.fusionsoft: debug
    org.springframework.security: DEBUG
    jdbc:
      resultsettable: INFO
      sqltiming: OFF
      sqlonly: INFO
      audit: OFF
      resultset: OFF
      connection: OFF
    net:
      sf:
        log4jdbc: WARN