spring:
  application:
    name: lea-api-common

  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://localhost:3306/cnd?CharacterEncoding=UTF-8
    username: viaura
    password: money

  sql:
    init:
      mode: never

jwt:
  secret: "QWApA/UT9UwgqbnIANd74/HEhd2JikcU9xjqEpgMAYY="
  access-token-validity-seconds: 1209600  # 14 days
  refresh-token-validity-seconds: 2592000 # 30 days
  issuer: "cnd-dev"

logging:
  file:
    name: logs/lea-api-common.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%X{requestId}] %-5level %logger{36} - %msg%n"
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{requestId}] %-5level %logger{36} - %msg%n"
  level:
    root: INFO
    com.fusionsoft: DEBUG
    org.springframework.security: DEBUG
    jdbc:
      resultsettable: INFO
      sqltiming: OFF
      sqlonly: INFO
      audit: OFF
      resultset: OFF
      connection: OFF
    net:
      sf:
        log4jdbc: WARN

mybatis:
  mapper-locations: classpath:mapper/**/*.xml   # XML 매퍼 경로
  type-aliases-package: com.fusionsoft.cnd.lea.api.common.domain.entity      # DTO/Entity 패키지
  configuration:
    map-underscore-to-camel-case: true          # 컬럼명 → 카멜케이스 자동 매핑