
DROP TABLE IF EXISTS USER_ROLES;
DROP TABLE IF EXISTS ROLES;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS REFRESH_TOKENS;

CREATE TABLE ROLES (
    ROLE_NAME VARCHAR(50) NOT NULL PRIMARY KEY COMMENT '역할 명'
);

-- 본사, 총판, 사이트 매니저들 테이블
CREATE TABLE USERS (
    UID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '매니저 고유번호',
    USER_ID VARCHAR(50) NOT NULL COMMENT '매니저 ID',
    USER_NAME VARCHAR(50) NOT NULL COMMENT '사용자 이름',
    PASSWORD VARCHAR(255) NOT NULL COMMENT '비밀번호',
    EMAIL VARCHAR(50) NOT NULL COMMENT '이메일 주소',
    PHONE VARCHAR(20) NOT NULL COMMENT '전화번호',
    ENABLED BOOLEAN NOT NULL DEFAULT TRUE COMMENT '활성/비활성 매니저 여부',
    REG_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일',
    UPD_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '마지막 변경일'
);

CREATE TABLE USER_ROLES (
    UID BIGINT NOT NULL COMMENT '사용자 고유번호',
    ROLE_NAME VARCHAR(50) NOT NULL,
    PRIMARY KEY (UID, ROLE_NAME),
    FOREIGN KEY (UID) REFERENCES USERS(UID) ON DELETE CASCADE,
    FOREIGN KEY (ROLE_NAME) REFERENCES ROLES(ROLE_NAME) ON DELETE CASCADE
);

--
-- CREATE TABLE REFRESH_TOKENS (
--    RID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT 'refresh token 고유번호',
--    TOKEN VARCHAR(256) NOT NULL,
--    EXPIRY_DATE TIMESTAMP NOT NULL ,
--    USER_ID VARCHAR(50) NOT NULL,
--    REG_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일'
-- );
